export const spacesData = [
  {
    id: 1,
    categories: ["Facial", "Especializados"],
    image: "/featured-projects/featured-work-1.jpg",
    date: "90 minutos",
    name: "Medicina Estética",
    location: "Tratamientos Avanzados",
    clientImage: "/spaces/client-1.jpeg",
    clientName: "Total 6-8 sesiones / 1 por semana",
    route: "/services/medicina-estetica",
  },
  {
    id: 2,
    categories: ["Facial"],
    image: "/featured-projects/featured-work-2.jpg",
    date: "75 minutos",
    name: "Tratamientos Faciales",
    location: "Cuidado Facial",
    clientImage: "/spaces/client-2.jpeg",
    clientName: "Total 6-8 sesiones / 1 por semana",
    route: "/services/tratamientos-faciales",
  },
  {
    id: 3,
    categories: ["Corporal"],
    image: "/featured-projects/featured-work-3.jpg",
    date: "60 minutos",
    name: "Tratamientos Corporales",
    location: "Bienestar Corporal",
    clientImage: "/spaces/client-3.jpeg",
    clientName: "Total 8-10 sesiones / 2 por semana",
    route: "/services/tratamientos-corporales",
  },
  {
    id: 4,
    categories: ["Especializados"],
    image: "/featured-projects/featured-work-4.jpg",
    date: "30-45 minutos",
    name: "Depilación Láser",
    location: "Depilación Definitiva",
    clientImage: "/spaces/client-4.jpeg",
    clientName: "Total 6-8 sesiones / cada 4-6 semanas",
    route: "/services/depilacion-laser",
  },
  {
    id: 5,
    categories: ["Facial", "Especializados"],
    image: "/featured-projects/featured-work-1.jpg",
    date: "60 minutos",
    name: "Dermatología Estética",
    location: "Salud de la Piel",
    clientImage: "/spaces/client-5.jpeg",
    clientName: "Total 4-6 sesiones / cada 2 semanas",
    route: "/services/dermatologia-estetica",
  },
  {
    id: 6,
    categories: ["Especializados"],
    image: "/featured-projects/featured-work-2.jpg",
    date: "45 minutos",
    name: "Tratamientos Capilares",
    location: "Cuidado Capilar",
    clientImage: "/spaces/client-6.jpeg",
    clientName: "Total 6-8 sesiones / 1 por semana",
    route: "/services/tratamientos-capilares",
  },
  {
    id: 7,
    categories: ["Facial"],
    image: "/featured-projects/featured-work-3.jpg",
    date: "90 minutos",
    name: "Rejuvenecimiento Facial",
    location: "Anti-Edad",
    clientImage: "/spaces/client-7.jpeg",
    clientName: "Total 6-8 sesiones / 1 por semana",
    route: "/services/rejuvenecimiento-facial",
  },
  {
    id: 8,
    categories: ["Especializados"],
    image: "/featured-projects/featured-work-4.jpg",
    date: "60 minutos",
    name: "Nutrición Estética",
    location: "Bienestar Integral",
    clientImage: "/spaces/client-1.jpeg",
    clientName: "Seguimiento mensual / 3-6 meses",
    route: "/services/nutricion-estetica",
  },
];
